

# error status codes:
BAD_GATEWAY = 502
BAD_REQUEST = 400
UNAUTHORIZED = 401
FORBIDDEN = 403
NOT_FOUND = 404
ERROR_PAYLOAD_TOO_LARGE = 413
ERROR_INTERNAL_SERVER_ERROR = 500
ERROR_INSUFFICIENT_STORAGE = 507


# HTTP methods containing bodies
BODY_METHODS = ('POST', 'PUT')


