# basic success:
OK = 200

# error status codes:
BAD_REQUEST = 400
UNAUTHORIZED = 401
FORBIDDEN = 403
NOT_FOUND = 404
PRECONDITION_FAILED = 412
PAYLOAD_TOO_LARGE = 413
TOO_MANY_REQUESTS = 429
INTERNAL_SERVER_ERROR = 500
BAD_GATEWAY = 502
INSUFFICIENT_STORAGE = 507


# HTTP methods containing bodies
BODY_METHODS = ('POST', 'PUT')
